#!/bin/bash
ls -al
pwd
echo "Running the packer script now..!!"
echo .
echo .
packer build packer.json
echo .
echo .
terraform init
terraform apply --var-file test.tfvars -var 'aws_access_key=AKIATGPLVSTS6XXGEUUL' -var 'aws_secret_key=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' --auto-approve
echo "Infra Built Sucessfully....!!!"
docker -H 10.1.1.220 run --rm -dit --name nginx1 --hostname nginx1 -p 8000:80 nginx:latest
